// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace message {

static const char* VerifyCodeService_method_names[] = {
  "/message.VerifyCodeService/GetVerifyCode",
};

std::unique_ptr< VerifyCodeService::Stub> VerifyCodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VerifyCodeService::Stub> stub(new VerifyCodeService::Stub(channel, options));
  return stub;
}

VerifyCodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVerifyCode_(VerifyCodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VerifyCodeService::Stub::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyCodeReq& request, ::message::GetVerifyCodeRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::GetVerifyCodeReq, ::message::GetVerifyCodeRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVerifyCode_, context, request, response);
}

void VerifyCodeService::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyCodeReq* request, ::message::GetVerifyCodeRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::GetVerifyCodeReq, ::message::GetVerifyCodeRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, std::move(f));
}

void VerifyCodeService::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyCodeReq* request, ::message::GetVerifyCodeRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::GetVerifyCodeRsp>* VerifyCodeService::Stub::PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::GetVerifyCodeReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::GetVerifyCodeRsp, ::message::GetVerifyCodeReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVerifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::GetVerifyCodeRsp>* VerifyCodeService::Stub::AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::GetVerifyCodeReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVerifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VerifyCodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VerifyCodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VerifyCodeService::Service, ::message::GetVerifyCodeReq, ::message::GetVerifyCodeRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VerifyCodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::GetVerifyCodeReq* req,
             ::message::GetVerifyCodeRsp* resp) {
               return service->GetVerifyCode(ctx, req, resp);
             }, this)));
}

VerifyCodeService::Service::~Service() {
}

::grpc::Status VerifyCodeService::Service::GetVerifyCode(::grpc::ServerContext* context, const ::message::GetVerifyCodeReq* request, ::message::GetVerifyCodeRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

